export const LIST = "LIST_MANAGER_DATA";
export const LIST_SUCCESS = "LIST_MANAGER_DATA_SUCCESS";
export const LIST_FAILED = "LIST_MANAGER_DATA_FAILED";

export const ADD = "ADD_MANAGER_DATA";
export const ADD_SUCCESS = "ADD_MANAGER_DATA_SUCCESS";
export const ADD_FAILED = "ADD_MANAGER_DATA_FAILED";

export const EDIT = "EDIT_MANAGER_DATA";
export const EDIT_SUCCESS = "EDIT_MANAGER_DATA_SUCCESS";
export const EDIT_FAILED = "EDIT_MANAGER_DATA_FAILED";

export const DELETE = "DELETE_MANAGER_DATA";
export const DELETE_SUCCESS = "DELETE_MANAGER_DATA_SUCCESS";
export const DELETE_FAILED = "DELETE_MANAGER_DATA_FAILED";

export const STATISTIC = "STATISTIC_MANAGER_DATA";
export const STATISTIC_SUCCESS = "STATISTIC_MANAGER_DATA_SUCCESS";
export const STATISTIC_FAILED = "STATISTIC_MANAGER_DATA_FAILED";

export const RESET = "RESET_MONEY";
export const RESET_SUCCESS = "RESET_MONEY_SUCCESS";
export const RESET_FAILED = "RESET_MONEY_FAILED";

export const SETTING = "SETTING_LIMIT";
export const SETTING_SUCCESS = "SETTING_LIMIT_SUCCESS";
export const SETTING_FAILED = "SETTING_LIMIT_FAILED";

export const RESET_DATA = "RESET_DATA_EMPLOYEE";
